import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import { connect, ResolveThunks } from "react-redux";
import { ApplicationState } from "../redux/rootReducer";
import { setUser } from "../redux/User/userAction";

interface OwnProps {
  name: string | null | undefined;
}

const mapStateToProps = ({ user: { name } }: ApplicationState) => {
  return {
    name,
  };
};

const mapDispatchToProps = {
  setUser,
};

type Props = OwnProps &
  ResolveThunks<typeof mapDispatchToProps> &
  ReturnType<typeof mapStateToProps>;

const Home = ({ name, setUser }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{name}</div>
        <button
          onClick={() => {
            setUser({
              id: 1,
              name: "changed",
              phoneNumber: 123123,
              email: "mr_momocom@gmail.com",
              role: 4,
            });
          }}
        >
          try dispatching action
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default connect(mapStateToProps, mapDispatchToProps)(Home);
